# Generated by Django 3.2.8 on 2022-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_diarista_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarista',
            name='tipo_logradouro',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
